FeedBackTracking/Controllers/Managing_agentController.cs
using FeedBackTracking.Models;
using FeedBackTracking.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace FeedBackTracking.Controllers
{    [Authorize(Roles="managing agent")]
    public class Managing_agentController : Controller
    {
        public ActionResult ManagingDashboard()
        {
            return View();
        }

        public ActionResult Add_MCST()
        {
            return View();
        }

        public ActionResult MCST_Listing()
        {
            return View();
        }

        public ActionResult Add_Tenant()
        {
            return View();
        }
        public ActionResult Tenant_Listing()
        {
            return View();
        }

        public ActionResult Add_LTC()
        {
            return View();
        }

        public ActionResult LTC_Listing()
        {
            return View();
        }

        public ActionResult Add_FeedBack()
        {
            return View();
        }
        public ActionResult FeedBack_Listing()
        {
            return View();
        }

        public ActionResult Add_Category()
        {
            return View();
        }
        public ActionResult Category_Listing()
        {
            return View();
        }

        public ActionResult Add_Location()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add_Location(Add_Location_Category lc)
        {
            string user=Membership.GetUser().ToString();
            DateTime date = DateTime.Now;
            Managing_agent_repository.Add_Loc(lc, user, date);
            string message = "SUCCESS";
            return Json(new { Message = message, JsonRequestBehavior.AllowGet });  
        }
       
        public JsonResult Get_Location(string id)
        {
            List<Add_Location_Category> lst = new List<Add_Location_Category>();
            lst = Managing_agent_repository.ReturnMList<Add_Location_Category>().ToList();
            return Json(lst, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Logout_M()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login", "Account");
        }
	}
}

FeedBackTracking/Views/Managing_agent/Add_Category.cshtml
@model FeedBackTracking.Models.Add_Feedback_Category

@{
    ViewBag.Title = "Add_Category";
    Layout = "~/Views/Shared/_ManagingLayout.cshtml";
}

<html>
<head>
    <style type="text/css">
        .form-style-9 {
            max-width: 100%;
            max-height: 946px;
            background: #FAFAFA;
            padding: 30px;
            margin: 0px auto;
            box-shadow: 1px 1px 25px rgba(0, 0, 0, 0.35);
            border-radius: 10px;
            border: 6px solid #376195;
        }

            .form-style-9 ul {
                padding: 0;
                margin: 0;
                list-style: none;
            }

                .form-style-9 ul li {
                    display: block;
                    margin-bottom: 10px;
                    min-height: 35px;
                }

                    .form-style-9 ul li .field-style {
                        box-sizing: border-box;
                        -webkit-box-sizing: border-box;
                        -moz-box-sizing: border-box;
                        padding: 8px;
                        outline: none;
                        border: 1px solid #B0CFE0;
                        -webkit-transition: all 0.30s ease-in-out;
                        -moz-transition: all 0.30s ease-in-out;
                        -ms-transition: all 0.30s ease-in-out;
                        -o-transition: all 0.30s ease-in-out;
                    }

                        .form-style-9 ul li .field-style:focus {
                            box-shadow: 0 0 5px #B0CFE0;
                            border: 1px solid #B0CFE0;
                        }

                    .form-style-9 ul li .field-split {
                        width: 49%;
                    }

                    .form-style-9 ul li .field-full {
                        width: 100%;
                    }

                    .form-style-9 ul li input.align-left {
                        float: left;
                    }

                    .form-style-9 ul li input.align-right {
                        float: right;
                    }

                    .form-style-9 ul li textarea {
                        width: 100%;
                        height: 100px;
                    }

        .pd {
        }

        .gd {
        }

        .cd {
        }

        .pd1 {
            margin-top: 48px;
        }

        .gd1 {
            margin-top: 48px;
        }

        .cd1 {
            margin-top: 48px;
        }

        .text {
            color: #305A72;
        }

        .form-style-9 ul li input[type="button"],
        .form-style-9 ul li input[type="submit"] {
            -moz-box-shadow: inset 0px 1px 0px 0px #376195;
            -webkit-box-shadow: inset 0px 1px 0px 0px #376195;
            box-shadow: inset 0px 1px 0px 0px #376195;
            background-color: #376195;
            border: 1px solid #376195;
            display: inline-block;
            cursor: pointer;
            color: #FFFFFF;
            padding: 8px 80px;
            text-decoration: none;
            font: 12px Arial, Helvetica, sans-serif;
            margin-left: 79px;
            margin-top: 0px;
        }

            .form-style-9 ul li input[type="button"]:hover,
            .form-style-9 ul li input[type="submit"]:hover {
                background: linear-gradient(to bottom, #2D77A2 5%, #337DA8 100%);
                background-color: #376195;
            }

        .span1 {
        }

        label {
            color: #305A72;
        }

        .b1 {
            color: #305A72;
        }

        .d1 {
        }

        .d2 {
            margin-top: 12px;
        }
    </style>


</head>
<body>
    <div class="d1">
        @using(Html.BeginForm("Add_Category","Managing_agentController",FormMethod.Post,new{@class="form-style-9"}))
       {
            <span style=" font-family:Arial">
                <h3 class="text">Add Category</h3></span>
                    <div style="  margin-top:10px;padding-left: 10px; padding-right: 10px;">
                        <ul class="pd">
                            <li>
                                @Html.TextBoxFor(model=>model.Name,new{ @class="field-style field-split align-left",@placeholder="Enter Location"})
                                @Html.ValidationMessageFor(model=>model.Name)
                                <input type="submit" value="Add" />
                            </li>
                        </ul>
                    </div>

       }
        </div>
            <div class="d2">

            </div>

        </body>
    </html>

FeedBackTracking/Views/Managing_agent/Add_Location.cshtml
@model FeedBackTracking.Models.Add_Location_Category

@{
    ViewBag.Title = "Add_Category";
    Layout = "~/Views/Shared/_ManagingLayout.cshtml";
    
}

<html>
<head>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css0">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.jqueryui.min.css">
    <style type="text/css">
        table, td, th {
            border: 1px solid #cdcdd1;
            text-align: center;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            padding: 15px;
        }

        th {
            background-color: #376195;
            color: white;
        }

        .btn {
            -moz-box-shadow: inset 0px 1px 0px 0px #376195;
            -webkit-box-shadow: inset 0px 1px 0px 0px #376195;
            box-shadow: inset 0px 1px 0px 0px #376195;
            background-color: #376195;
            border: 1px solid #376195;
            display: inline-block;
            cursor: pointer;
            color: #FFFFFF;
            padding: 7px 38px;
            text-decoration: none;
            font: 12px Arial, Helvetica, sans-serif;
            margin-left: 14px;
            margin-top: 0px;
            margin-bottom: 10px;
        }

        .field-style {
            box-sizing: border-box;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            padding: 8px;
            outline: none;
            border: 1px solid #B0CFE0;
            -webkit-transition: all 0.30s ease-in-out;
            -moz-transition: all 0.30s ease-in-out;
            -ms-transition: all 0.30s ease-in-out;
            -o-transition: all 0.30s ease-in-out;
        }

            .field-style:focus {
                box-shadow: 0 0 5px #B0CFE0;
                border: 1px solid #B0CFE0;
            }

        .field-split {
            width: 210px;
            height: 30px;
        }

        .text {
            color: #376195;
        }
        .form-style-9 {
            max-width: 100%;
            max-height: 946px;
            background: #FAFAFA;
            padding: 30px;
            margin: 0px auto;
            box-shadow: 1px 1px 25px rgba(0, 0, 0, 0.35);
            border-radius: 10px;
            border: 6px solid #376195;
        }

            .form-style-9 ul {
                padding: 0;
                margin: 0;
                list-style: none;
            }

                .form-style-9 ul li {
                    display: block;
                    margin-bottom: 10px;
                    min-height: 35px;
                }

                    .form-style-9 ul li .field-style {
                        box-sizing: border-box;
                        -webkit-box-sizing: border-box;
                        -moz-box-sizing: border-box;
                        padding: 8px;
                        outline: none;
                        border: 1px solid #B0CFE0;
                        -webkit-transition: all 0.30s ease-in-out;
                        -moz-transition: all 0.30s ease-in-out;
                        -ms-transition: all 0.30s ease-in-out;
                        -o-transition: all 0.30s ease-in-out;
                    }

                        .form-style-9 ul li .field-style:focus {
                            box-shadow: 0 0 5px #B0CFE0;
                            border: 1px solid #B0CFE0;
                        }

                    .form-style-9 ul li .field-split {
                        width: 49%;
                    }

                    .form-style-9 ul li .field-full {
                        width: 100%;
                    }

                    .form-style-9 ul li input.align-left {
                        float: left;
                    }

                    .form-style-9 ul li input.align-right {
                        float: right;
                    }

                    .form-style-9 ul li textarea {
                        width: 100%;
                        height: 100px;
                    }

        .pd {
        }

        .gd {
        }

        .cd {
        }

        .pd1 {
            margin-top: 48px;
        }

        .gd1 {
            margin-top: 48px;
        }

        .cd1 {
            margin-top: 48px;
        }

        .text {
            color: #305A72;
        }

        .form-style-9 ul li input[type="button"],
        .form-style-9 ul li input[type="submit"] {
            -moz-box-shadow: inset 0px 1px 0px 0px #376195;
            -webkit-box-shadow: inset 0px 1px 0px 0px #376195;
            box-shadow: inset 0px 1px 0px 0px #376195;
            background-color: #376195;
            border: 1px solid #376195;
            display: inline-block;
            cursor: pointer;
            color: #FFFFFF;
            padding: 8px 80px;
            text-decoration: none;
            font: 12px Arial, Helvetica, sans-serif;
            margin-left: 79px;
            margin-top: 0px;
        }

            .form-style-9 ul li input[type="button"]:hover,
            .form-style-9 ul li input[type="submit"]:hover {
                background: linear-gradient(to bottom, #2D77A2 5%, #337DA8 100%);
                background-color: #376195;
            }

        .span1 {
        }

        label {
            color: #305A72;
        }

        .b1 {
            color: #305A72;
        }

        .d1 {
        }

        .d2 {
            margin-top: 12px;
        }
    </style>

  
</head>
<body>
    <div class="d1">
        <div class="form-style-9">
            <span style=" font-family:Arial">
                <h3 class="text">Add Location</h3>
            </span>
            <div style="  margin-top:10px;padding-left: 10px; padding-right: 10px;">
                <ul class="pd">
                    <li>
                        @Html.TextBoxFor(model => model.Name, new { @class = "field-style field-split align-left", @placeholder = "Enter Location", @id = "locationname" })
                        @Html.ValidationMessageFor(model => model.Name)
                        <input type="button" value="Add" id="btnsave" />
                    </li>
                </ul>
            </div>

        </div>
    </div>
    <div class="d2">
        <table id="tblStudent" class="tblStudent">
            <thead>
                <tr>
                    <th>
                        Location Name
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Action
                    </th>

                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.jqueryui.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#tblStudent').DataTable();
        });
    </script>
    <script src="~/Scripts/jquery-3.3.1.js"></script>
        <script type="text/javascript">
            $(function () {
                LoadData();
                $("#btnsave").click(function () {
                    var std = {
                                Name : $("#locationname").val()
                              };
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Add_Location")',
                        data:  JSON.stringify(std) ,
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        success: function () {
                            // alert("Data has been added successfully.");  
                            LoadData();
                        },
                        error: function () {
                            alert("Error while inserting data");
                        }
                    });
                    return false;
                });
            });

            function LoadData()
            {
                $(".tblStudent tbody tr").remove();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Get_Location")',
                    dataType: 'json',
                    data: { id: '' },
                    success: function (data) {
                        var items = '';
                        $.each(data, function (i, item) {
                            var rows = "<tr>"
                            + "<td class='prtoducttd'>" + item.Name + "</td>"
                            @*+ "<td class='prtoducttd'>" + @Html.ActionLink("Edit", "Edit_Location") + "</td>"*@
                            + "<td class='prtoducttd'>" + item.Is_Active + "</td>"
                             
                            
                           
                            + "</tr>";
                            $('.tblStudent tbody').append(rows);
                        });
                    },
                    error: function (ex) {
                        var r = jQuery.parseJSON(response.responseText);
                        alert("Message: " + r.Message);
                        alert("StackTrace: " + r.StackTrace);
                        alert("ExceptionType: " + r.ExceptionType);
                    }
                });
                return false;
            }

        </script>
    
</body>
</html>

FeedBackTracking/Views/Managing_agent/Add_MCST.cshtml
@model FeedBackTracking.Models.Mcst_Staff_Data
@{
    ViewBag.Title = "Add_MCST";
    Layout = "~/Views/Shared/_ManagingLayout.cshtml";
}

<html>
<head>
    <title></title>
    <style type="text/css">
        .form-style-9 {
            max-width: 100%;
            max-height: 946px;
            background: #FAFAFA;
            padding: 4px;
            margin: -10px auto;
            box-shadow: 1px 1px 25px rgba(0, 0, 0, 0.35);
            border-radius: 10px;
            border: 6px solid #376195;
        }

            .form-style-9 ul {
                padding: 0;
                margin: 0;
                list-style: none;
            }

                .form-style-9 ul li {
                    display: block;
                    margin-bottom: 29px;
                    min-height: 35px;
                    margin-left: 23px;
                }

                    .form-style-9 ul li .field-style {
                        box-sizing: border-box;
                        -webkit-box-sizing: border-box;
                        -moz-box-sizing: border-box;
                        padding: 8px;
                        outline: none;
                        border: 1px solid #B0CFE0;
                        -webkit-transition: all 0.30s ease-in-out;
                        -moz-transition: all 0.30s ease-in-out;
                        -ms-transition: all 0.30s ease-in-out;
                        -o-transition: all 0.30s ease-in-out;
                    }

                        .form-style-9 ul li .field-style:focus {
                            box-shadow: 0 0 5px #B0CFE0;
                            border: 1px solid #B0CFE0;
                        }

                    .form-style-9 ul li .field-split {
                        width: 49%;
                    }

                    .form-style-9 ul li .field-full {
                        width: 100%;
                    }

                    .form-style-9 ul li input.align-left {
                        float: left;
                    }

                    .form-style-9 ul li input.align-right {
                       
                    }

                    .form-style-9 ul li textarea {
                        width: 100%;
                        height: 100px;
                    }

        .pd {
        }

        .gd {
        }

        .cd {
        }

        .pd1 {
            margin-top: 48px;
        }

        .gd1 {
            margin-top: 48px;
        }

        .cd1 {
            margin-top: 48px;
        }

        .text {
            color: #305A72;
        }

        .form-style-9 ul li input[type="button"],
        .form-style-9 ul li input[type="submit"] {
            -moz-box-shadow: inset 0px 1px 0px 0px #3985B1;
            -webkit-box-shadow: inset 0px 1px 0px 0px #3985B1;
            box-shadow: inset 0px 1px 0px 0px #3985B1;
            background-color: #216288;
            border: 1px solid #17445E;
            display: inline-block;
            cursor: pointer;
            color: #FFFFFF;
            padding: 8px 80px;
            text-decoration: none;
            font: 12px Arial, Helvetica, sans-serif;
            margin-left: 375px;
            margin-top: 10px;
        }

            .form-style-9 ul li input[type="button"]:hover,
            .form-style-9 ul li input[type="submit"]:hover {
                background: linear-gradient(to bottom, #2D77A2 5%, #337DA8 100%);
                background-color: #28739E;
            }

        .span1 {
        }

        label {
            color: #305A72;

        }
        .b1 {
            color: #305A72;
        }
    </style>


</head>
<body>

    @*<form class="form-style-9">*@
    @using (Html.BeginForm("Add_MCST", "Managing_agent", FormMethod.Get, new { @class = "form-style-9" }))
    {
        <span style=" font-family:Arial">
            <h3 class="text">ADD MCST STAFF</h3>
        </span>
        <div style="border:1px solid #305A72; border-radius:10px; margin-top:10px;padding-left: 10px;
    padding-right: 10px;">
           
                
                   <b class="b1">DETAILS</b> 
                        
                            <div class="pd1">

                                <ul class="pd">
                                    <li>
                                        @Html.LabelFor(model=>model.Name)
                                        @Html.TextBoxFor(model => model.Name, new { @class = "field-style field-split align-right", style = "margin-left:91px" })
                                        @Html.ValidationMessageFor(model=>model.Name)

                                    </li>
                                    <li>

                                        @Html.LabelFor(model => model.Email)
                                        @Html.TextBoxFor(model => model.Email, new { @class = "field-style field-split align-right", style = "margin-left: 42px" })
                                        @Html.ValidationMessageFor(model => model.Email)
                                    </li>
                                    <li>
                                       
                                        @Html.LabelFor(model => model.Phone_number)
                                        @Html.TextBoxFor(model => model.Phone_number, new { @class = "field-style field-split align-right", style = "margin-left: 34px" })
                                        @Html.ValidationMessageFor(model => model.Phone_number)

                                    </li>
                                    <li>
                                        
                                        @Html.LabelFor(model => model.Password)
                                        @Html.TextBoxFor(model => model.Password, new { @class = "field-style field-split align-right", style = "margin-left: 68px" })
                                        @Html.ValidationMessageFor(model => model.Password)
                                    </li>
                                    <li>
                                        @Html.LabelFor(model=>model.Property)
                                        @Html.DropDownList("Please Select", new List<SelectListItem>
                                                      {
                                                        new SelectListItem{ Text="User", Value = "User" },
                                                        new SelectListItem{ Text="Admin", Value = "Admin" },                                                        
                                                      }, new { @class = "field-style field-split align-left", style = "margin-left: 73px" }) 
                                        @Html.ValidationMessageFor(model=>model.Property)
                                    </li>
                                    <li>
                                        @Html.LabelFor(model=>model.Role)
                                        @Html.DropDownList("Please Select",new List<SelectListItem>
                                                      {
                                                        new SelectListItem{ Text="User", Value = "User" },
                                                        new SelectListItem{ Text="Admin", Value = "Admin" },                                                        
                                                      }, new { @class = "field-style field-split align-left", style = "margin-left: 100px" }) 
                                        @Html.ValidationMessageFor(model => model.Role)
                                    </li>
                                    <li>
                                        @Html.LabelFor(model=>model.Feedback_Category)
                                        @Html.DropDownList("Please Select",new List<SelectListItem>
                                                      {
                                                        new SelectListItem{ Text="User", Value = "User" },
                                                        new SelectListItem{ Text="Admin", Value = "Admin" },                                                        
                                                      }, new { @class = "field-style field-split align-left",style="margin-left:10px" }) 
                                        @Html.ValidationMessageFor(model => model.Feedback_Category)
                                    </li>
                                </ul>
                            </div>
        </div>

        <ul>
            <li>
                <input type="submit" value="Add" />
            </li>
        </ul>
    }
    

</body>
</html>

FeedBackTracking/Views/Managing_agent/Location_Listing.cshtml
@model IEnumerable<FeedBackTracking.Models.Add_Location_Category>


<style>
    table, td, th {
        border: 1px solid #cdcdd1;
        text-align: center;
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        padding: 15px;
    }

    th {
        background-color: #376195;
        color: white;
    }

    .btn {
        -moz-box-shadow: inset 0px 1px 0px 0px #376195;
        -webkit-box-shadow: inset 0px 1px 0px 0px #376195;
        box-shadow: inset 0px 1px 0px 0px #376195;
        background-color: #376195;
        border: 1px solid #376195;
        display: inline-block;
        cursor: pointer;
        color: #FFFFFF;
        padding: 7px 38px;
        text-decoration: none;
        font: 12px Arial, Helvetica, sans-serif;
        margin-left: 14px;
        margin-top: 0px;
        margin-bottom: 10px;
    }

    .field-style {
        box-sizing: border-box;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        padding: 8px;
        outline: none;
        border: 1px solid #B0CFE0;
        -webkit-transition: all 0.30s ease-in-out;
        -moz-transition: all 0.30s ease-in-out;
        -ms-transition: all 0.30s ease-in-out;
        -o-transition: all 0.30s ease-in-out;
    }

        .field-style:focus {
            box-shadow: 0 0 5px #B0CFE0;
            border: 1px solid #B0CFE0;
        }

    .field-split {
        width: 210px;
        height: 30px;
    }

    .text {
        color: #376195;
    }
</style>

@*@using (Html.BeginForm("Display", "Main", FormMethod.Post))
    {
        <div>
            <span class="text" ><b>Search Name: </b></span>@Html.TextBox("Search", ViewBag.FilterValue as string, new { @class = "field-style field-split align-left", @placeholder = "FirstName" })
            <input type="submit" class="btn" value="Find" />
        </div>
    }*@
<table id="example" class="display">
    <tr>
        <th>
            S.NO
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
       
        <th>
            Action
        </th>
        <th>
            Status
        </th>
    </tr>
    @{
        int i = 1;

        foreach (var item in Model)
        {
            <tr>
                <td>
                    @i.
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                
                <td>
                    @Html.ActionLink("Edit", "Edit", new { @id = @item.Id }) |
                    @*@Html.ActionLink("Details", "Details", new { @id = @item.UserId }) |*@
                    @Html.ActionLink("Delete", "Delete", new { @id = @item.Id }, new { onclick = "return confirm('Are you sure you want to delete this Location ?');" })
                </td>
                @if (@item.Is_Active == "Active")
                {
                    <td style="color:green">
                        @Html.DisplayFor(modelItem => item.Is_Active)
                    </td>
                }
                else
                {
                    <td style="color:red">
                        @Html.DisplayFor(modelItem => item.Is_Active)
                    </td>
                }

            </tr>
                i = i + 1;
        }
    }

FeedBackTracking/Views/Managing_agent/ManagingDashboard.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ManagingLayout.cshtml";
}

<h2>Index</h2>

FeedBackTracking/Views/Managing_agent/Tenant_Listing.cshtml
@{
    ViewBag.Title = "Tenant_Listing";
    Layout = "~/Views/Shared/_ManagingLayout.cshtml";
}
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css0">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.jqueryui.min.css">
<style>
    table, td, th {
        border: 1px solid #cdcdd1;
        text-align: center;
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        padding: 15px;
    }

    th {
        background-color: #376195;
        color: white;
    }
</style>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.jqueryui.min.js"></script>
<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>
<table id="example" class="display">
    <thead>
        <tr>
            <th>
                S.No
            </th>
            <th>
                Name
            </th>
            <th>
                Email
            </th>
            <th>
                Property Name
            </th>
            <th>
                Company Name
            </th>
            <th>
                Unit No
            </th>
            <th>
                MCST Council
            </th>
            <th>
                Action
            </th>
            <th>
                Status
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>Ranosys</td>
            <td>ranosys@gmail.com</td>
            <td>Property Name</td>
            <td>Ranosys</td>
            <td>334</td>
            <td>Yes</td>
            <td>@Html.ActionLink("Edit", "") | @Html.ActionLink("Detail", "")</td>
            <td>Active</td>
        </tr>
    </tbody>
</table>